### ISSUE TITLE
Overlay disappears too fast to click wiki link.

### ISSUE THREAD

**Issue by danielniccoli** [whalehub/noita-map-viewer#5]
Overlay disappears too fast to click wiki link.

**Comment by whalehub** [comment]
I can't reproduce this issue; the delay is long enough for me to click the wiki links. That being said, you can adjust the delay to your liking by changing the value here: https://github.com/whalehub/noita-map-viewer/blob/master/js/scripts.js#L358

**Comment by whalehub** [comment]
> It doesn't work for me. Even if I set this from 500 to 10000, it still disappears almost immediately. Tested with Firefox and Chromium. What browser are you using?

I'm using a Chromium-based browser called Vivaldi.

**Comment by whalehub** [comment]
> Overlays work in https://noita.datahoarder.dev/
> 
> But they don't properly work for the source code in your repository. I also noticed that your website has different code running, than in this repository.

The code on the website is identical, it has just been [minified](https://en.wikipedia.org/wiki/Minification_(programming)#Web_development) to improve loading times.
