### ISSUE TITLE
Map image isn't loading in personal map hosting

### ISSUE THREAD

**Issue by ArticulatedDrunk** [whalehub/noita-map-viewer#7]
Can't get my iiif3 file to work in the personal map hosting no matter what I do, I've tried webby, devd, and caddy and I can get them all to host the icons but never the actual map. I don't know if I'm just doing it wrong or what but I could use some clarification on the instructions, I really don't do web hosting normally.

**Comment by whalehub** [comment]
Can you please paste the content of your `info.json` here?

**Comment by ArticulatedDrunk** [comment]
Last tutorial I tried was caddy so it's set to what that use.

{
  "@context": "http://iiif.io/api/image/3/context.json",
  "id": "http://localhost:2015",
  "type": "ImageService3",
  "profile": "level0",
  "protocol": "http://iiif.io/api/image",
  "tiles": [
    {
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32,
        64,
        128,
        256
      ],
      "width": 256
    }
  ],
  "width": 51968,
  "height": 74496
}

**Comment by whalehub** [comment]
You need to change the value of the `id` field to the folder which contains the images, e.g. http://localhost:2015/iiif3
